version: '3.7'
services:
    app_amqp:
        depends_on:
            - amqp
            - db
    app_http:
        depends_on:
            - amqp
            - db
    amqp:
        image: rabbitmq:3-management
        container_name: com_ligilo_amqp
        restart: on-failure
        ports:
            - $AMQP_PORT:5672
            - $AMQP_MANAGEMENT_PORT:15672
    db:
        image: mariadb:11
        container_name: com_ligilo_db
        restart: on-failure
        ports:
            - $DB_PORT:3306
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=app
            - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
volumes:
    db_data:
        name: com_ligilo_db_data
